---
galaxy_info:
  author: "Rida Ridane"
  description: "GÃ¨re les paquets kube (kubect, kubadm, kubelet)"
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions: ["bullseye", "bookworm"]
    - name: Ubuntu
      versions: ["20.04", "22.04", "24.04"]
  galaxy_tags: ["hosts", "network", "bootstrap"]
dependencies: []